TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.2 #modified velocity from 0.18 to 0.2
  min_vel_x: 0.1 #modified from 0.08 to 0.1

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.105 #modified from o.05 to 0.105
  yaw_goal_tolerance: 3.14 #modified from 0.17 to 3.14

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
