move_base:
  TrajectoryPlannerROS:

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.105 #modified from 0.1 to 0.105
    yaw_goal_tolerance: 3.14 #modified from 0.05 to 3.14

  DWAPlannerROS:

    # Goal Tolerance Parametes
    xy_goal_tolerance: 0.105 #modified from o.05 to 0.105
    yaw_goal_tolerance: 3.14 #modified from 0.17 to 3.14
    latch_xy_goal_tolerance: false

    # Trajectory Scoring Parameters
    path_distance_bias: 32.0
    goal_distance_bias: 20.0
    occdist_scale: 0.02
    forward_point_distance: 0.105 # modified from 0.325 to 0.105
    #for the goal point from the center to place additional point infront of the bot
    stop_time_buffer: 0.2
    scaling_speed: 0.25
    max_scaling_factor: 0.2

  global_costmap:
    global_frame: map
    robot_base_frame: base_footprint

    update_frequency: 5.0 #modified from 10.0 to 5.0
    publish_frequency: 5.0 #modified from 10.0 to 5.0
    transform_tolerance: 0.5

    static_map: true

    use_dijkstra: false #use A* for path finding
   
    inflation_layer: {inflation_radius: 0.2 , cost_scaling_factor: 50.0} 
    #modified from inf = 1 to 0.2 and csf = 3.0 to 50 

  local_costmap:
    global_frame: odom
    robot_base_frame: base_footprint

    update_frequency: 5.0 #modified from 10.0 to 5.0
    publish_frequency: 5.0 # modified from 10.0 to 5.0
    transform_tolerance: 0.5  

    static_map: false  
    rolling_window: true
    width: 3
    height: 3
    resolution: 0.02 #modified from 0.05 to 0.02 to find path in narrow pathways

    inflation_layer: {inflation_radius: 0.2 , cost_scaling_factor: 50.0} 
    #modified from inf = 1 to 0.2 and csf = 3.0 to 50

move_base:
  base_local_planner: cnavfn/NavfnROS



