DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.22
  min_vel_x: -0.22

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.28 #modified from 0.22 to 0.28
  min_vel_trans:  0.2 #modified from 0.11 to 0.2

  max_vel_theta: 2.75
  min_vel_theta: 1.37

  acc_lim_x: 3 #modified from 2.5 to 3
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parametes
  xy_goal_tolerance:  0.105 #modified from o.05 to 0.105
  yaw_goal_tolerance: 3.14 #modified from 0.17 to 3.14
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.105  0.105 # modified from 0.325 to 0.105
    #for the goal point from the center to place additional point infront of the bot
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
